### ISSUE TITLE
Will this package work with Laravel 5.4?

### ISSUE THREAD

**Issue by benrolfe** [laravelnews/laravel-twbs4#1]

**Comment by wilburpowery** [comment]
If I'm not mistaking, No it won't work. Laravel 5.4 does not have the preset command. You would have to install and configure it manually.

**Comment by paulredmond** [comment]
> If I'm not mistaking, No it won't work. Laravel 5.4 does not have the preset command. You would have to install and configure it manually.

Correct, so what you can do is copy over the views and adjust the right NPM modules to `package.json`.

I don't know what `package.json` diff is between 5.4 and 5.5, so it's just a matter of removing `bootstrap-sass` and adding `bootstrap` and `popper.js`. See [this method](https://github.com/laravelnews/laravel-twbs4/blob/master/src/BootstrapPreset.php#L27-L33) for details on the NPM package versions.
