### ISSUE TITLE
WordPress Support

### ISSUE THREAD

**Issue by ninjaparade** [laravelnews/laravel-twbs4#12]
See title.

**Comment by ericlbarnes** [comment]
WordPress is GOAT 🐐

**Comment by ninjaparade** [comment]
@ericbarnes, totally agree. Wonder why @paulredmond REFUSES to support it?

**Comment by ericlbarnes** [comment]
@ninjaparade Maybe we should fork it?

**Comment by ninjaparade** [comment]
Maybe @paulredmond should realize the internet is run by WordPress and support it.

**Comment by paulredmond** [comment]
You merely adopted WordPress. I was born in it, molded by it.

**Comment by ericlbarnes** [comment]
I can see this is going to take a dark turn.

**Comment by paulredmond** [comment]
Aw man, I already started a WPArtisan package 📦
