### ISSUE TITLE
Laravel Mix fails when installing laravel-twbs4 after React

### ISSUE THREAD

**Issue by valentinogagliardi** [laravelnews/laravel-twbs4#14]
Thanks for this preset!

I've found a little problem.

If you run

```bash
php artisan preset react
```

on a fresh Laravel installation the preset takes care of modifying `webpack.mix.js` by adding

```javascript
mix.react('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');
```

When installing `laravel-twbs4` after React, your preset reverts back `webpack.mix.js` by changing again the configuration file to

```javascript
mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css');
```

By running `npm i && npm run dev` an error will be thrown:

```javascript
ERROR in ./resources/assets/js/components/Example.js
Module build failed: SyntaxError: Unexpected token (7:12)

   5 |     render() {
   6 |         return (
>  7 |             <div className="container">
     |             ^
   8 |                 <div className="row">
   9 |                     <div className="col-md-8 col-md-offset-2">
  10 |                         <div className="panel panel-default">
```

The problem could be solved by installing `laravel-twbs4` **before** React. But I think it is worth noting.

By the way, thanks again for this preset!

**Comment by paulredmond** [comment]
Thanks for the report. Yeah, it's a bit tricky and I don't have a good idea for a solution. If you think of anything feel free to submit a PR!
