### ISSUE TITLE
Do not install this package with NodeJS 9

### ISSUE THREAD

**Issue by erwin-van-maasakkers** [laravelnews/laravel-twbs4#16]
I posted an earlier issue: github.....v4.5.3/win32-x64-59_binding.node doesnt exist.
I found a solution; I installed this package with NodeJS 9, and i've got an error:
 Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node":

I downgraded to NodeJS 8 and that solved the problem. Not sure it is a packageproblem, but this might be an solution.

**Comment by paulredmond** [comment]
Thanks, using Yarn might be helpful, I use it for Laravel projects and it works out pretty well.
