### ISSUE TITLE
How can I used full jQuery?

### ISSUE THREAD

**Issue by sollidsnake** [laravelnews/laravel-twbs4#17]
I see that on commit #13 you require the slim version of jQuery. 
But what if I need to use the full version? How can I do it?

**Comment by jayaregalinada** [comment]
By changing on your `resources/assets/js/boostrap.js`

From

``` js
... 
    window.$ = window.jQuery = require('jquery/dist/jquery.slim');
...
```

into

``` js
...
    window.$ = window.jQuery = require('jquery');
...
```

Then, compile your assets.

**Comment by paulredmond** [comment]
Thanks @jayaregalinada!
