### ISSUE TITLE
jQuery.slim dependency not found

### ISSUE THREAD

**Issue by MarlonEtiene** [laravelnews/laravel-twbs4#18]
Can anyone help me with this error

`> @ dev /home/marlon/www/eclesia
> npm run development

> @ development /home/marlon/www/eclesia
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting                                                                         

 WARNING  Compiled with 1 warnings                                                          00:58:54

This dependency was not found:

* jquery/dist/jquery.slim in ./resources/assets/js/bootstrap.js

To install it, you can run: npm install --save jquery/dist/jquery.slim
       Asset     Size  Chunks                    Chunk Names
  /js/app.js  1.08 MB       0  [emitted]  [big]  /js/app
/css/app.css   178 kB       0  [emitted]         /js/app

WARNING in ./resources/assets/js/bootstrap.js
Module not found: Error: Can't resolve 'jquery/dist/jquery.slim' in '/home/marlon/www/eclesia/resources/assets/js'
 @ ./resources/assets/js/bootstrap.js 13:29-63
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss`

Thank you

**Comment by paulredmond** [comment]
Hmm, I was able to test it with both Yarn and NPM on a new project and it worked. I would suggest blowing away `node_modules/` and trying an `npm install`, or better yet, use Yarn, it's better at resolving packages IMO.

What is the output of this command for you?
```
ls -la node_modules/jquery/dist/
```

For me it's:

```
ls -la node_modules/jquery/dist/
total 1760
drwxr-xr-x   9 paul  staff     288 Dec  5 22:16 .
drwxr-xr-x  10 paul  staff     320 Dec  5 22:16 ..
-rw-r--r--   1 paul  staff   11197 Mar 20  2017 core.js
-rw-r--r--   1 paul  staff  268039 Mar 20  2017 jquery.js
-rw-r--r--   1 paul  staff   86659 Mar 20  2017 jquery.min.js
-rw-r--r--   1 paul  staff  131666 Mar 20  2017 jquery.min.map
-rw-r--r--   1 paul  staff  215256 Mar 20  2017 jquery.slim.js
-rw-r--r--   1 paul  staff   69597 Mar 20  2017 jquery.slim.min.js
-rw-r--r--   1 paul  staff  104583 Mar 20  2017 jquery.slim.min.map
```

**Comment by paulredmond** [comment]
@MarlonEtiene my other thought, is this an existing project? Can you paste your package.json file as a code snippet here? jQuery slim might not be in your version, one way around that would be to update the `resources/assets/js/bootstrap.js` with this if you don't mind using full jQuery:

```js
window.$ = window.jQuery = require('jquery');
```

**Comment by MarlonEtiene** [comment]
@paulredmond I am sorry, I was very tired I was worked about 14 hours wit non stop.
I have not seen in the error message the solution for the problem

'To install it, you can run: npm install --save jquery/dist/jquery.slim'

After execute it, the problem gone away.

Sorry to bother you, there is no problem.
