### ISSUE TITLE
after installing and running npm run dev I get error

### ISSUE THREAD

**Issue by chriz74x** [laravelnews/laravel-twbs4#19]
ERROR in multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
Module not found: Error: Can't resolve 'babel-loader'

I am not specyfing any babel loader in app.scss or app.js so it must be in your imports, you are not resolving the path.

**Comment by paulredmond** [comment]
Hey there 👋 

Can you please share your package.json file? I need at least some sort of information other than the error to help you.

Have you tried re-installing npm modules?

The `laravel-mix` package depends on `babel-loader` (https://github.com/JeffreyWay/laravel-mix/blob/02a9826b172435d1698f479ea66c986ec9aa4d69/package.json#L33)

**Comment by paulredmond** [comment]
Also, did you run `npm install` as outlined in the README?

```
npm install && npm run dev
```

**Comment by chriz74x** [comment]
Hello, I will send you on Sunday

Il giorno ven 22 dic 2017 alle 20:55 Paul Redmond <notifications@github.com>
ha scritto:

**Comment by paulredmond** [comment]
Closing until more info is provided.

**Comment by chriz74x** [comment]
sorry for the delay. Here's the file

2017-12-22 21:07 GMT+01:00 Paul Redmond <notifications@github.com>:
