### ISSUE TITLE
Move to laravel-frontend-presets

### ISSUE THREAD

**Issue by m1guelpf** [laravelnews/laravel-twbs4#2]
Hi!
Firstly, thank you for creating this!
I am one of the administrators of the [laravel-frontend-presets](https://github.com/laravel-frontend-presets) organization, were we host presets built by the community.
Would you like to move this preset to the organization? [If you have doubts, see FAQs about rights, permissions](https://laravel-frontend-presets.github.io/#faq).
Thank you again!

**Comment by ericlbarnes** [comment]
Thanks for the offer, but I want to keep this under the Laravel News organization account.

**Comment by m1guelpf** [comment]
@ericbarnes Cool! Let us know if you change your mind.

**Comment by paulredmond** [comment]
@m1guelpf feel free to create an empty repo with the readme linking here, or maintaining a fork works too.

**Comment by ericlbarnes** [comment]
@m1guelpf @OwenMelbz 

Like I said I'm not interested in changing the ownership but I should have time this weekend to a submit a PR to your site repo to add this one to it: 
https://github.com/laravel-frontend-presets/laravel-frontend-presets.github.io

Let me know if that works for you.
