### ISSUE TITLE
jQuery slim is being loaded

### ISSUE THREAD

**Issue by simplenotezy** [laravelnews/laravel-twbs4#20]
I have an issue. I cannot use `$.ajax` because of this commit: https://github.com/laravelnews/laravel-twbs4/commit/1e89f61adb57ebb6f2815e859a8602229451610d

How can I force it to load the normal jQuery library?

**Comment by simplenotezy** [comment]
Caused me some headache debugging why `$.ajax` was not working. Found https://github.com/laravelnews/laravel-twbs4/issues/17

**Comment by paulredmond** [comment]
Thanks, I documented it in #21. You can learn more about slim in this release post - https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/
