### ISSUE TITLE
Popper not loaded

### ISSUE THREAD

**Issue by ghost** [laravelnews/laravel-twbs4#22]
The line `window.Popper = require('popper.js/dist/umd/popper');` in _bootstrap.js_ doesn't load anything. It throws error 404.

**Comment by paulredmond** [comment]
> It throws error 404

@danielgraziani91 The bootstrap.js file isn't meant to be part of an HTTP request, you need to build the script which ends up being:

```
npm install && npm run dev
```

Then in your layout template, load the app.js file:

```blade
<script src="{{ asset('js/app.js') }}"></script>
```

I'll reopen this if you submit an error / stacktrace that you are running into with steps to reproduce. Thanks!

**Comment by paulredmond** [comment]
I was able to install the preset without issue using the latest Laravel `v5.5.28`. Cannot reproduce.

**Comment by paulredmond** [comment]
When I was upgrading to `v4.0.0-beta.3` I noticed a 404 for the Popper.js sourcemap. If that's your issue, I removed it by calling sourcemaps() in the `webpack.mix.js` file:

```js
let mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/assets/js/app.js', 'public/js').sourceMaps();
mix.sass('resources/assets/sass/app.scss', 'public/css');
```

This was the sourcemap 404 I was seeing:

![screen shot 2018-01-01 at 4 56 45 pm](https://user-images.githubusercontent.com/177773/34472040-041cfb82-ef15-11e7-864f-733a668bb3f5.png)
