### ISSUE TITLE
bs4 with bs3 colors

### ISSUE THREAD

**Issue by mokhosh** [laravelnews/laravel-twbs4#24]
it's a bit strange. i have bs4 now but primary and other colors have remained the same.

UPDATE: sorry i now saw the variables you modified. but now that i have a checkbox, i see it's not stylized either. am i still missing something?

UPDATE: turns out i was missing something. those stylized checkboxes are custom controls. i'm awfully sorry :D

**Comment by safir187** [comment]
now that i have a checkbox, i see it's not stylized either
