### ISSUE TITLE
Missing popper.js requirement

### ISSUE THREAD

**Issue by wilfalken** [laravelnews/laravel-twbs4#28]
For those (like me) who have a broken Laravel (5.5 with auth) interface even after doing all the _**laravel-twbs4**_ install steps, that's because _**Bootstrap 4**_ is requiring _**popper.js**_.

To repair this, you need to download **_popper.js_** on Bootstrap's homepage (for example), put popper.js in _**public/js**_ folder.

OR add this line in your project's _**root**_ folder, file _**webpack.mix.js**_. I have put _**popper.js**_ in 

> "ressources/assets/js/templates/bootstrap4"

, so I need to write :

> before Bootstrap 4, **webpack.mix.js** was like this:

`mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css');`

> To have Bootstrap 4 work as expected:

`mix.js('resources/assets/js/app.js', 'resources\assets\js\templates\bootstrap4\popper.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css');`

That's not really an issue, as this is solved, but maybe this package developper could add some requirement so _**popper.js**_ could be installed with the package transparently...

**Comment by paulredmond** [comment]
Popper.js gets installed in the `package.json` file when using this preset.

https://github.com/laravelnews/laravel-twbs4/blob/bc77e48bce692055c71200d7d3791d66a0697191/src/bootstrap-stubs/bootstrap.js#L4
