### ISSUE TITLE
Laravel 5.6 install issue

### ISSUE THREAD

**Issue by marty12321** [laravelnews/laravel-twbs4#31]
When trying to install on new laravel 5.6, got this error:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravelnews/laravel-twbs4 1.3.0 requires laravel/framework ~5.5.0 -> satisfiable by laravel/framework[5.5.x-dev].
    - laravelnews/laravel-twbs4 1.3.1 requires laravel/framework ~5.5.0 -> satisfiable by laravel/framework[5.5.x-dev].
    - laravelnews/laravel-twbs4 1.3.x-dev requires laravel/framework ~5.5.0 -> satisfiable by laravel/framework[5.5.x-dev].
    - Conclusion: don't install laravel/framework 5.5.x-dev
    - Installation request for laravelnews/laravel-twbs4 ^1.3 -> satisfiable by laravelnews/laravel-twbs4[1.3.0, 1.3.1, 1.3.x-dev].

Installation failed, reverting ./composer.json to its original content.

**Comment by paulredmond** [comment]
Hey @marty12321, Laravel 5.6 now includes Bootsrap 4.0 out-of-the-box, so this preset is only needed if you want to use Laravel 5.5 LTS, which is still Bootstrap 3.
