### ISSUE TITLE
How to upgrade to laravel 5.6

### ISSUE THREAD

**Issue by noobling** [laravelnews/laravel-twbs4#33]
I think it would be helpful for a lot of people if we could start a discussion on how to upgrade to Laravel 5.6 with this package. Does anyone have any thoughts?

**Comment by paulredmond** [comment]
Hey @noobling thanks for the note, this package isn't needed for `>= Laravel 5.6` because Bootstrap 4 now ships with Laravel as of 5.6.

See #30, #31, #32
